services:
  - type: web
    name: twitter-bookmark-scraper
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/project/.render/chrome/opt/google/chrome/google-chrome
    disk:
      name: render-disk
      mountPath: /opt/render/project/.render
      sizeGB: 1
