services:
  - type: web
    name: twitter-bookmark-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWITTER_SCRAPER_TOKEN
        sync: false
      - key: TWITTER_COOKIES
        sync: false
      - key: TWITTER_USER_ID
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: playwright-cache
      mountPath: /opt/render/.cache
      sizeGB: 1